config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :watchers
  resources :posts  do
    resources :comments
  end
  
  get '/login', to: "sessions#new", as: "login"
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  
  get '/watchers' => 'pages#watchers'
  get '/about' => 'pages#about'
  get '/welcome' => 'pages#welcome'
  root 'pages#about'

end

app/models/watcher.rb
class Watcher < ActiveRecord::Base
	has_many :comments
	has_many :posts

end

 t.string :email,              null: false, default: ""

app/controllers/watchers_controller.rb
class WatchersController < ApplicationController
  before_action :set_watcher, only: [:show, :edit, :update, :destroy]

  def index
    @watchers = Watcher.all
  end

  def show
    @watchers = Watcher.find params[:id]
  end

  def new
    @watcher = Watcher.new
  end



  def edit
  end

  def create
    @watcher = Watcher.new(watcher_params)
    # if pw == pw conf

    respond_to do |format|
      if @watcher.save
        format.html { redirect_to @watcher, notice: 'Watcher was successfully created.' }
        
      else
        format.html { render :new }
        
      end
    end
  end

  def update
    respond_to do |format|
      if @watcher.update(watcher_params)
        format.html { redirect_to @watcher, notice: 'Watcher was successfully updated.' }
       
      else
        format.html { render :edit }
        
      end
    end
  end

  def destroy
    @watcher.destroy
    respond_to do |format|
      format.html { redirect_to watchers_url, notice: 'Watcher was successfully destroyed.' }
    end
  end

  private

    def set_watcher
      @watcher = Watcher.find(params[:id])
    end

    def watcher_params
      params.require(:watcher).permit(:username, :fname, :lname, :password, :password_confirmation, :email)
    end
end

app/helpers/watchers_helper.rb
module WatchersHelper
end

app/views/watchers/_form.html.erb
<%= form_for(@watcher) do |f| %>
  <% if @watcher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watcher.errors.count, "error") %> prohibited this watcher from being saved:</h2>

      <ul>
      <% @watcher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/watchers/edit.html.erb
<h1>Editing Watcher</h1>

<%= render 'form' %>

<%= link_to 'Show', @watcher %> |
<%= link_to 'Back', watchers_path %>

app/views/watchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Brother's Keepers - The Watchers</h1>
<h3>You were put here to protect us, but who protects us from you?</h3>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @watchers.each do |watcher| %>
      <tr>
        <td><%= watcher.username %></td>
        <td><%= watcher.fname %></td>
        <td><%= watcher.lname %></td>
        <td><%= watcher.password %></td>
        <td><%= watcher.email %></td>
        <td><%= link_to 'Show', watcher %></td>
        <td><%= link_to 'Edit', edit_watcher_path(watcher) %></td>
        <td><%= link_to 'Destroy', watcher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watcher', new_watcher_path %>

app/views/watchers/new.html.erb
<h1>New Watcher</h1>

<%= render 'form' %>

<%= link_to 'Back', watchers_path %>

app/views/watchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @watcher.username %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @watcher.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @watcher.lname %>
</p>

<p>
  <strong>Password:</strong>
  <%= @watcher.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @watcher.email %>
</p>

<%= link_to 'Edit', edit_watcher_path(@watcher) %> |
<%= link_to 'Welcome', welcome_path %>