config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :watchers
  resources :posts  do
    resources :comments
  end
  
  get '/login', to: "sessions#new", as: "login"
  post   '/login'   => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'
  
  get '/watchers' => 'pages#watchers'
  get '/about' => 'pages#about'
  get '/welcome' => 'pages#welcome'
  root 'pages#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :puffs
	belongs_to :watcher
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    # @post.watcher = current_watcher.username
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # @watcher = Watcher.find(params[:id])
    @post=Post.find(params[:id])
  end

  # GET /posts/new
  def new
    if session[:user_id]=true
    @post = Post.new
  else
    flash[:notice]="Please sign in again"
    redirect_to login_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.watcher_id = current_watcher  
    # @post = current_watcher.post.build(params[:post])
    @post.user_id = session[:id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        
      else
        format.html { render :new }
      end
    end
  end

  # def current_watcher
  #         Watcher.find(session[:watcher_id])
  # end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
        
      end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
     
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content).merge(watcher: current_watcher)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
 

  <div class="form-group">
     <%= f.label :kind %><br>
     <%= f.select :kind,  ["text","image url"], {}, class: "form-control" %> 
  </div>


  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, :rows=>10, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
		<p>
			<h2> 

			  <%= link_to post.title, post_path(post)  %> 
			</h2>
		</p> 
		 

		<p>
			<% if post.kind == 'image' %>
			
			   
			   <%= image_tag post.content, style: "width 100%" %>
			<% else %>

			<%= simple_format post.content %>
			<% end %>
		</p>
		
		<p class="text-muted">
			<small>
				Posted on <%= post.created_at. to_formatted_s(:long) %> 
			</small>
			
		</p>  

		

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Watcher ID </th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>

      <tr>
        <td><%= post.title %></td>
      
        
        <td><%= truncate(post.content, length: 50) %></td>
      
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Post', new_post_path %>
<br>

app/views/posts/new.html.erb
 <h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %> 

app/views/posts/show.html.erb
 	

<% if notice.present? %>

<p class="alert alert-info">
	<%= notice %></p>

<p>
	
	
	<h2> <%= @post.watcher %> </h2>
<% end %>
 
 <%= render 'post', post: @post %>